/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.26                      *
*        Compiled Aug 14 2014, 10:10:08                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: song16.c                                              *
* Font:        ËÎÌå                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: E:\¼Ó×Ö¿â.txt                                   *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
#define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsong16;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_0043[ 16] =   /* code 0043, LATIN CAPITAL LETTER C */
{
    ________,
    ________,
    ________,
    __XXXXX_,
    _X____X_,
    _X____X_,
    X_______,
    X_______,
    X_______,
    X_______,
    X_______,
    _X____X_,
    _X___X__,
    __XXX___,
    ________,
    ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_004F[ 16] =   /* code 004F, LATIN CAPITAL LETTER O */
{
    ________,
    ________,
    ________,
    __XXX___,
    _X___X__,
    X_____X_,
    X_____X_,
    X_____X_,
    X_____X_,
    X_____X_,
    X_____X_,
    X_____X_,
    _X___X__,
    __XXX___,
    ________,
    ________
};

/* Start of unicode area <Letterlike Symbols> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_2103[ 32] =   /* code 2103, DEGREE CELSIUS */
{
    _XX_____, ________,
    X__X___X, XXXX_X__,
    X__X_XX_, ____XX__,
    _XX_XX__, _____X__,
    ____X___, _____X__,
    ___XX___, ________,
    ___XX___, ________,
    ___XX___, ________,
    ___XX___, ________,
    ___XX___, ________,
    ___XX___, ________,
    ____X___, ________,
    ____XX__, _____X__,
    _____XX_, ____X___,
    _______X, XXXX____,
    ________, ________
};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_4E00[ 32] =   /* code 4E00, <CJK Ideograph, First> */
{
    ________, ________,
    ________, ________,
    ________, ________,
    ________, ________,
    ________, ________,
    ________, ________,
    ________, ________,
    XXXXXXXX, XXXXXXX_,
    ________, ________,
    ________, ________,
    ________, ________,
    ________, ________,
    ________, ________,
    ________, ________,
    ________, ________,
    ________, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_4E0A[ 32] =   /* code 4E0A */
{
    ______X_, ________,
    ______X_, ________,
    ______X_, ________,
    ______X_, ________,
    ______X_, ________,
    ______X_, ________,
    ______XX, XXXXX___,
    ______X_, ________,
    ______X_, ________,
    ______X_, ________,
    ______X_, ________,
    ______X_, ________,
    ______X_, ________,
    ______X_, ________,
    XXXXXXXX, XXXXXXX_,
    ________, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_4E0B[ 32] =   /* code 4E0B */
{
    ________, ________,
    XXXXXXXX, XXXXXXX_,
    ______X_, ________,
    ______X_, ________,
    ______X_, ________,
    ______X_, ________,
    ______X_, _X______,
    ______X_, __X_____,
    ______X_, ___X____,
    ______X_, ____X___,
    ______X_, ____X___,
    ______X_, ________,
    ______X_, ________,
    ______X_, ________,
    ______X_, ________,
    ______X_, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_4E16[ 32] =   /* code 4E16 */
{
    ______X_, __X_____,
    ___X__X_, __X_____,
    ___X__X_, __X_____,
    ___X__X_, __X_____,
    ___X__X_, __X_____,
    XXXXXXXX, XXXXXXX_,
    ___X__X_, __X_____,
    ___X__X_, __X_____,
    ___X__X_, __X_____,
    ___X__X_, __X_____,
    ___X__XX, XXX_____,
    ___X____, ________,
    ___X____, ________,
    ___X____, ________,
    ___XXXXX, XXXXXX__,
    ________, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_4E3B[ 32] =   /* code 4E3B */
{
    ______X_, ________,
    _______X, ________,
    ________, ________,
    _XXXXXXX, XXXXXX__,
    _______X, ________,
    _______X, ________,
    _______X, ________,
    _______X, ________,
    __XXXXXX, XXXXX___,
    _______X, ________,
    _______X, ________,
    _______X, ________,
    _______X, ________,
    _______X, ________,
    XXXXXXXX, XXXXXXX_,
    ________, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_4E50[ 32] =   /* code 4E50 */
{
    ________, __X_____,
    ________, XXXX____,
    ___XXXXX, ________,
    ___X____, ________,
    ___X___X, ________,
    __X____X, ________,
    __X____X, ________,
    __XXXXXX, XXXXXX__,
    _______X, ________,
    ____X__X, __X_____,
    ____X__X, ___X____,
    ___X___X, ____X___,
    __X____X, _____X__,
    _X_____X, _____X__,
    _____X_X, ________,
    ______X_, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_4E56[ 32] =   /* code 4E56 */
{
    ________, _XXX____,
    ___XXXXX, X_______,
    _______X, ________,
    _______X, ________,
    XXXXXXXX, XXXXXXX_,
    _______X, ________,
    ____X__X, __X_____,
    ____X__X, __X__X__,
    _XXXX__X, __X_X___,
    ____X__X, __XX____,
    ____X__X, __X___X_,
    ___XX__X, __X___X_,
    XXX_X__X, ___XXXX_,
    _______X, ________,
    _______X, ________,
    _______X, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_4F53[ 32] =   /* code 4F53 */
{
    ____X___, _X______,
    ____X___, _X______,
    ____X___, _X______,
    ___X____, _X______,
    ___X_XXX, XXXXXX__,
    __XX____, _X______,
    __XX____, XXX_____,
    _X_X____, XXX_____,
    X__X___X, _X_X____,
    ___X___X, _X_X____,
    ___X__X_, _X__X___,
    ___X_X_X, XXXX_X__,
    ___XX___, _X____X_,
    ___X____, _X______,
    ___X____, _X______,
    ___X____, _X______
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5077[ 32] =   /* code 5077 */
{
    ____X___, _X______,
    ____X___, X_X_____,
    ____X__X, ___X____,
    ___X__X_, ____X___,
    ___X_X_X, XXXX_XX_,
    __XX____, ________,
    __XX__XX, XX___X__,
    _X_X__X_, _X_X_X__,
    X__X__X_, _X_X_X__,
    ___X__XX, XX_X_X__,
    ___X__X_, _X_X_X__,
    ___X__X_, _X_X_X__,
    ___X__XX, XX_X_X__,
    ___X__X_, _X___X__,
    ___X__X_, _X_X_X__,
    ___X__X_, XX__X___
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_513F[ 32] =   /* code 513F */
{
    ____X___, _X______,
    ____X___, _X______,
    ____X___, _X______,
    ____X___, _X______,
    ____X___, _X______,
    ____X___, _X______,
    ____X___, _X______,
    ____X___, _X______,
    ____X___, _X______,
    ____X___, _X______,
    ____X___, _X______,
    ___X____, _X____X_,
    ___X____, _X____X_,
    __X_____, _X____X_,
    _X______, __XXXXX_,
    X_______, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5154[ 32] =   /* code 5154 */
{
    ____X___, ________,
    ____X___, ________,
    ____XXXX, XXX_____,
    ___X____, __X_____,
    __X_____, _X______,
    _XXXXXXX, XXXXX___,
    X_X____X, ____X___,
    __X____X, ____X___,
    __X____X, ____X___,
    __XXXXXX, XXXXX___,
    __X___X_, X___X___,
    _____X__, X_X_____,
    ____X___, X__X____,
    ___X____, X__X__X_,
    __X_____, X_____X_,
    XX______, _XXXXXX_
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5168[ 32] =   /* code 5168 */
{
    _______X, ________,
    _______X, ________,
    ______X_, X_______,
    _____X__, _X______,
    ____X___, __X_____,
    ___X____, ___X____,
    __X_XXXX, XXX_X___,
    XX_____X, _____XX_,
    _______X, ________,
    _______X, ________,
    ___XXXXX, XXXX____,
    _______X, ________,
    _______X, ________,
    _______X, ________,
    _XXXXXXX, XXXXXX__,
    ________, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5173[ 32] =   /* code 5173 */
{
    ___X____, ___X____,
    ____X___, ___X____,
    ____X___, __X_____,
    ________, ________,
    __XXXXXX, XXXXX___,
    _______X, ________,
    _______X, ________,
    _______X, ________,
    XXXXXXXX, XXXXXXX_,
    _______X, ________,
    ______X_, X_______,
    ______X_, X_______,
    _____X__, _X______,
    ____X___, __X_____,
    __XX____, ___XX___,
    XX______, _____XX_
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_51C0[ 32] =   /* code 51C0 */
{
    _______X, ________,
    _X_____X, ________,
    __X___XX, XXXX____,
    __X__X__, ___X____,
    ________, __X_____,
    ___X_XXX, XXXXXX__,
    ___X____, _X___X__,
    ___X____, _X___X__,
    __X_XXXX, XXXXXXX_,
    __X_____, _X___X__,
    XXX_____, _X___X__,
    __X__XXX, XXXXXX__,
    __X_____, _X___X__,
    __X_____, _X______,
    __X____X, _X______,
    ________, X_______
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5236[ 32] =   /* code 5236 */
{
    _____X__, _____X__,
    __X__X__, _____X__,
    __X__X__, _____X__,
    __XXXXXX, X_X__X__,
    _X___X__, __X__X__,
    _____X__, __X__X__,
    XXXXXXXX, XXX__X__,
    _____X__, __X__X__,
    _____X__, __X__X__,
    __XXXXXX, X_X__X__,
    __X__X__, X_X__X__,
    __X__X__, X_X__X__,
    __X__XX_, X____X__,
    __X__X_X, _____X__,
    _____X__, ___X_X__,
    _____X__, ____X___
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_52A0[ 32] =   /* code 52A0 */
{
    ___X____, ________,
    ___X____, ________,
    ___X____, ________,
    ___X____, _XXXXX__,
    XXXXXXX_, _X___X__,
    ___X__X_, _X___X__,
    ___X__X_, _X___X__,
    ___X__X_, _X___X__,
    ___X__X_, _X___X__,
    ___X__X_, _X___X__,
    ___X__X_, _X___X__,
    ___X__X_, _X___X__,
    __X___X_, _X___X__,
    __X___X_, _XXXXX__,
    _X__X_X_, _X___X__,
    X____X__, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5316[ 32] =   /* code 5316 */
{
    ____X___, X_______,
    ____X___, X_______,
    ____X___, X____X__,
    ___X____, X___X___,
    ___X____, X__X____,
    __XX____, X_X_____,
    __XX____, XX______,
    _X_X____, X_______,
    X__X___X, X_______,
    ___X__X_, X_______,
    ___X_X__, X_______,
    ___X____, X_____X_,
    ___X____, X_____X_,
    ___X____, X_____X_,
    ___X____, _XXXXXX_,
    ___X____, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_53C2[ 32] =   /* code 53C2 */
{
    ______X_, ________,
    _____X__, _X______,
    ____X___, __X_____,
    ___XXXXX, XXXX____,
    ______X_, ________,
    _XXXXXXX, XXXXXX__,
    ____X___, __X_____,
    ___X____, X__X____,
    __X___XX, ____X___,
    XX__XX__, _X___XX_,
    _______X, X_______,
    _____XX_, ___X____,
    ___XX___, __X_____,
    ________, XX______,
    _____XXX, ________,
    _XXXX___, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_53EA[ 32] =   /* code 53EA */
{
    ________, ________,
    ___XXXXX, XXXX____,
    ___X____, ___X____,
    ___X____, ___X____,
    ___X____, ___X____,
    ___X____, ___X____,
    ___X____, ___X____,
    ___X____, ___X____,
    ___XXXXX, XXXX____,
    ___X____, ___X____,
    ________, ________,
    ____X___, __X_____,
    ____X___, ___X____,
    ___X____, ____X___,
    __X_____, _____X__,
    _X______, _____X__
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5410[ 32] =   /* code 5410 */
{
    ________, _X______,
    ________, _X______,
    _XXXX___, _X______,
    _X__X___, _X______,
    _X__X___, _X______,
    _X__X___, _X______,
    _X__XXXX, XXXXXX__,
    _X__X___, _X______,
    _X__X___, _X______,
    _X__X___, _X______,
    _XXXX___, _X______,
    _X__X___, _X______,
    ________, _X______,
    ________, _X______,
    ____XXXX, XXXXXXX_,
    ________, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5426[ 32] =   /* code 5426 */
{
    ________, ________,
    _XXXXXXX, XXXXXX__,
    ________, X_______,
    _______X, ________,
    ______XX, ________,
    _____X_X, _XX_____,
    ____X__X, ___XX___,
    __XX___X, _____X__,
    XX_____X, ______X_,
    ________, ________,
    ___XXXXX, XXXX____,
    ___X____, ___X____,
    ___X____, ___X____,
    ___X____, ___X____,
    ___XXXXX, XXXX____,
    ___X____, ___X____
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5668[ 32] =   /* code 5668 */
{
    ________, ________,
    __XXXXX_, _XXXXX__,
    __X___X_, _X___X__,
    __X___X_, _X___X__,
    __XXXXX_, _XXXXX__,
    _______X, __X_____,
    _______X, ___X____,
    XXXXXXXX, XXXXXXX_,
    ______X_, X_______,
    ____XX__, _XX_____,
    __XX____, ___XX___,
    XX______, _____XX_,
    __XXXXX_, _XXXXX__,
    __X___X_, _X___X__,
    __X___X_, _X___X__,
    __XXXXX_, _XXXXX__
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5728[ 32] =   /* code 5728 */
{
    ______X_, ________,
    ______X_, ________,
    _____X__, ________,
    XXXXXXXX, XXXXXXX_,
    ____X___, ________,
    ____X___, _X______,
    ___X____, _X______,
    __XX____, _X______,
    _X_X_XXX, XXXXXX__,
    X__X____, _X______,
    ___X____, _X______,
    ___X____, _X______,
    ___X____, _X______,
    ___X____, _X______,
    ___XXXXX, XXXXXXX_,
    ___X____, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5883[ 32] =   /* code 5883 */
{
    __X_____, X_______,
    __X_____, _X______,
    __X___XX, XXXXX___,
    __X____X, ___X____,
    XXXXX___, X_X_____,
    __X__XXX, XXXXXXX_,
    __X_____, ________,
    __X___XX, XXXXX___,
    __X___X_, ____X___,
    __X___XX, XXXXX___,
    __X___X_, ____X___,
    __XXX_XX, XXXXX___,
    XXX____X, __X_____,
    _X_____X, __X___X_,
    ______X_, __X___X_,
    ____XX__, ___XXXX_
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5907[ 32] =   /* code 5907 */
{
    _____X__, ________,
    _____X__, ________,
    ____XXXX, XXXX____,
    ___XX___, __X_____,
    _XX__X__, _X______,
    ______XX, X_______,
    ___XXX__, _XXX____,
    XXX_____, ____XXX_,
    ___XXXXX, XXXX____,
    ___X___X, ___X____,
    ___X___X, ___X____,
    ___XXXXX, XXXX____,
    ___X___X, ___X____,
    ___X___X, ___X____,
    ___XXXXX, XXXX____,
    ___X____, ___X____
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5976[ 32] =   /* code 5976 */
{
    ___X____, ________,
    ___X____, ________,
    ___X__XX, XXXXX___,
    ___X____, X___X___,
    XXXXXX__, X__X____,
    __X__X__, X__X____,
    __X__X__, X_X_____,
    __X__X__, X_XXXX__,
    __X__X__, X____X__,
    _X__X___, X____X__,
    __X_X__X, _____X__,
    ___X___X, _____X__,
    __X_X__X, _____X__,
    _X___XX_, _____X__,
    X_____X_, __X_X___,
    _____X__, ___X____
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_597D[ 32] =   /* code 597D */
{
    ___X____, ________,
    ___X____, XXXXXX__,
    ___X____, _____X__,
    ___X____, ____X___,
    XXXXXX__, ___X____,
    __X__X__, __X_____,
    __X__X__, __X_____,
    __X__X_X, XXXXXXX_,
    __X__X__, __X_____,
    _X__X___, __X_____,
    __X_X___, __X_____,
    ___X____, __X_____,
    __X_X___, __X_____,
    _X___X__, __X_____,
    X____X__, X_X_____,
    ________, _X______
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5988[ 32] =   /* code 5988 */
{
    ___X____, ________,
    ___X__XX, XXXX____,
    ___X____, ___X____,
    ___X____, ___X____,
    XXXXXX_X, ___X____,
    __X__X_X, ___X____,
    __X__X_X, ___X____,
    __X__X_X, XXXXXX__,
    __X__X__, _____X__,
    _X__X___, _____X__,
    __X_X___, _____X__,
    ___X__XX, XXXX_X__,
    __X_X___, _____X__,
    _X___X__, _____X__,
    X____X__, __X_X___,
    ________, ___X____
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5A74[ 32] =   /* code 5A74 */
{
    ________, ________,
    __XXXXX_, XXXXX___,
    __X___X_, X___X___,
    __X_X_X_, X_X_X___,
    __X_X_X_, X_X_X___,
    __X_X_X_, X_X_X___,
    ___X_X__, _X_X____,
    _XX___X_, X___X___,
    ______X_, ________,
    _XXXXXXX, XXXXXX__,
    _____X__, __X_____,
    ____X___, _X______,
    ___XXX__, X_______,
    ______XX, X_______,
    _____XX_, _XXX____,
    __XXX___, ____X___
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5B50[ 32] =   /* code 5B50 */
{
    ________, ________,
    _XXXXXXX, XXXXX___,
    ________, ___X____,
    ________, __X_____,
    ________, _X______,
    _______X, X_______,
    _______X, ________,
    XXXXXXXX, XXXXXXX_,
    _______X, ________,
    _______X, ________,
    _______X, ________,
    _______X, ________,
    _______X, ________,
    _______X, ________,
    _____X_X, ________,
    ______X_, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5B66[ 32] =   /* code 5B66 */
{
    __X___X_, ____X___,
    ___X___X, ____X___,
    ___X___X, ___X____,
    ________, __X_____,
    _XXXXXXX, XXXXXXX_,
    _X______, ______X_,
    X_______, _____X__,
    ___XXXXX, XXX_____,
    ________, _X______,
    _______X, X_______,
    XXXXXXXX, XXXXXXX_,
    _______X, ________,
    _______X, ________,
    _______X, ________,
    _____X_X, ________,
    ______X_, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5B89[ 32] =   /* code 5B89 */
{
    ______X_, ________,
    _______X, ________,
    __XXXXXX, XXXXXX__,
    __X_____, _____X__,
    _X____X_, ____X___,
    ______X_, ________,
    ______X_, ________,
    XXXXXXXX, XXXXXXX_,
    _____X__, __X_____,
    ____X___, __X_____,
    ___XX___, _X______,
    _____XX_, _X______,
    _______X, X_______,
    ______X_, _XX_____,
    ____XX__, ___X____,
    _XXX____, ____X___
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5C0F[ 32] =   /* code 5C0F */
{
    _______X, ________,
    _______X, ________,
    _______X, ________,
    _______X, ________,
    _______X, ________,
    ___X___X, ___X____,
    ___X___X, ____X___,
    ___X___X, _____X__,
    __X____X, _____X__,
    __X____X, ______X_,
    _X_____X, ______X_,
    X______X, ______X_,
    _______X, ________,
    _______X, ________,
    _____X_X, ________,
    ______X_, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5C3F[ 32] =   /* code 5C3F */
{
    ________, ________,
    __XXXXXX, XXXXX___,
    __X_____, ____X___,
    __X_____, ____X___,
    __XXXXXX, XXXXX___,
    __X_____, X_______,
    __X_____, X_______,
    __X_____, X___X___,
    __X_XXX_, XX_X____,
    __X___X_, XXX_____,
    __X___X_, X_X_____,
    __X__X__, X_X_____,
    _X___X__, X__X____,
    _X__X___, X___X___,
    X__X__X_, X____X__,
    _______X, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5E8A[ 32] =   /* code 5E8A */
{
    _______X, ________,
    ________, X_______,
    __XXXXXX, XXXXXXX_,
    __X_____, ________,
    __X_____, X_______,
    __X_____, X_______,
    __X_XXXX, XXXXXX__,
    __X_____, X_______,
    __X____X, XX______,
    __X___X_, X_X_____,
    __X___X_, X_X_____,
    __X__X__, X__X____,
    _X__X___, X___X___,
    _X_X____, X____XX_,
    X_______, X_______,
    ________, X_______
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5EA6[ 32] =   /* code 5EA6 */
{
    _______X, ________,
    ________, X_______,
    __XXXXXX, XXXXXXX_,
    __X___X_, __X_____,
    __X___X_, __X_____,
    __XXXXXX, XXXXXX__,
    __X___X_, __X_____,
    __X___X_, __X_____,
    __X___XX, XXX_____,
    __X_____, ________,
    __X_XXXX, XXXX____,
    __X__X__, ___X____,
    _X____X_, __X_____,
    _X_____X, XX______,
    X____XX_, __XX____,
    __XXX___, ____XXX_
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5F00[ 32] =   /* code 5F00 */
{
    ________, ________,
    _XXXXXXX, XXXXXX__,
    ____X___, __X_____,
    ____X___, __X_____,
    ____X___, __X_____,
    ____X___, __X_____,
    ____X___, __X_____,
    XXXXXXXX, XXXXXXX_,
    ____X___, __X_____,
    ____X___, __X_____,
    ____X___, __X_____,
    ____X___, __X_____,
    ___X____, __X_____,
    ___X____, __X_____,
    __X_____, __X_____,
    _X______, __X_____
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5F0F[ 32] =   /* code 5F0F */
{
    ________, _X__X___,
    ________, _X___X__,
    ________, _X___X__,
    ________, _X______,
    XXXXXXXX, XXXXXXX_,
    ________, _X______,
    ________, _X______,
    __XXXXX_, _X______,
    ____X___, _X______,
    ____X___, _X______,
    ____X___, __X_____,
    ____X___, __X___X_,
    ____XXXX, ___X__X_,
    _XXXX___, ____X_X_,
    __X_____, _____XX_,
    ________, ______X_
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6293[ 32] =   /* code 6293 */
{
    ___X____, ____X___,
    ___X____, ___XXX__,
    ___X___X, XXXX____,
    ___X___X, _X_X____,
    XXXXXX_X, _X_X____,
    ___X___X, _X_X____,
    ___X___X, _X_X____,
    ___X_X_X, _X_X____,
    ___XX__X, _X_X____,
    __XX___X, _X__X___,
    XX_X___X, _X__X___,
    ___X___X, _X__X___,
    ___X___X, _X___X__,
    ___X__X_, _X___X__,
    _X_X__X_, _X____X_,
    __X__X__, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6342[ 32] =   /* code 6342 */
{
    ___X____, ________,
    ___X__XX, XXXXXXX_,
    ___X____, _X______,
    ___X____, _X______,
    XXXXXX_X, XXXXXX__,
    ___X____, X____X__,
    ___X____, X____X__,
    ___X_XXX, XXXXXXX_,
    ___XX___, ________,
    __XX____, ________,
    XX_X___X, XXXXXX__,
    ___X___X, _____X__,
    ___X___X, _____X__,
    ___X___X, _____X__,
    _X_X___X, XXXXXX__,
    __X____X, _____X__
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_63A7[ 32] =   /* code 63A7 */
{
    ___X____, _X______,
    ___X____, __X_____,
    ___X____, __X_____,
    ___X__XX, XXXXXXX_,
    XXXXX_X_, ______X_,
    ___X_X__, X__X_X__,
    ___X___X, ____X___,
    ___XX_X_, _____X__,
    __XX____, ________,
    XX_X___X, XXXXXX__,
    ___X____, __X_____,
    ___X____, __X_____,
    ___X____, __X_____,
    ___X____, __X_____,
    _X_X_XXX, XXXXXXX_,
    __X_____, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6446[ 32] =   /* code 6446 */
{
    ___X____, ________,
    ___X__XX, XXXXXXX_,
    ___X__X_, _X_X__X_,
    ___X__X_, _X_X__X_,
    XXXXX_XX, XXXXXXX_,
    ___X____, __X_____,
    ___X_X__, __X_____,
    ___XX__X, XXXXXX__,
    __XX____, __X_____,
    XX_X____, __X_____,
    ___X_XXX, XXXXXXX_,
    ___X____, _X______,
    ___X____, X___X___,
    ___X___X, _____X__,
    _X_X__XX, XXXXXXX_,
    __X____X, ______X_
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6447[ 32] =   /* code 6447 */
{
    ___X____, ____X___,
    ___X____, __XXXX__,
    ___X__XX, XX______,
    ___X____, _____X__,
    XXXXX_X_, _X___X__,
    ___X___X, __X_X___,
    ___X___X, XXXXXX__,
    ___XX_X_, __X_____,
    __XX____, __X_____,
    XX_X__XX, XXXXXXX_,
    ___X____, __X_____,
    ___X___X, __X__X__,
    ___X___X, __X__X__,
    ___X___X, __X__X__,
    _X_X___X, XXXXXX__,
    __X_____, _____X__
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6570[ 32] =   /* code 6570 */
{
    ____X___, __X_____,
    _X__X__X, __X_____,
    __X_X_X_, __X_____,
    ____X___, __XXXXX_,
    XXXXXXXX, _X___X__,
    __X_X_X_, _X___X__,
    _X__X__X, _X___X__,
    X___X___, X_X__X__,
    ___X____, __X_X___,
    XXXXXXX_, __X_X___,
    __X___X_, ___X____,
    _X____X_, ___X____,
    _XX__X__, __X_X___,
    ___XX___, __X_X___,
    __XX_X__, _X___X__,
    XX____X_, X_____X_
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_662F[ 32] =   /* code 662F */
{
    ___XXXXX, XXXX____,
    ___X____, ___X____,
    ___X____, ___X____,
    ___XXXXX, XXXX____,
    ___X____, ___X____,
    ___X____, ___X____,
    ___XXXXX, XXXX____,
    ________, ________,
    XXXXXXXX, XXXXXXX_,
    _______X, ________,
    ___X___X, ________,
    ___X___X, XXXXX___,
    ___X___X, ________,
    __X_X__X, ________,
    _X___X_X, ________,
    X_____XX, XXXXXXX_
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6696[ 32] =   /* code 6696 */
{
    ________, __XXXX__,
    _____XXX, XX______,
    _XXXX_X_, _X___X__,
    _X__X__X, __X_X___,
    _X__X___, ________,
    _X__X_XX, XXXXXX__,
    _XXXX___, X_______,
    _X__X___, X_______,
    _X__XXXX, XXXXXXX_,
    _X__X__X, ________,
    _X__X__X, XXXXX___,
    _XXXX_X_, X___X___,
    _X__X_X_, _X_X____,
    _____X__, __X_____,
    ____X___, XX_XX___,
    ______XX, _____XX_
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_66F2[ 32] =   /* code 66F2 */
{
    _____X__, _X______,
    _____X__, _X______,
    _____X__, _X______,
    _____X__, _X______,
    _XXXXXXX, XXXXXX__,
    _X___X__, _X___X__,
    _X___X__, _X___X__,
    _X___X__, _X___X__,
    _X___X__, _X___X__,
    _XXXXXXX, XXXXXX__,
    _X___X__, _X___X__,
    _X___X__, _X___X__,
    _X___X__, _X___X__,
    _X___X__, _X___X__,
    _XXXXXXX, XXXXXX__,
    _X______, _____X__
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6709[ 32] =   /* code 6709 */
{
    ______X_, ________,
    ______X_, ________,
    XXXXXXXX, XXXXXXX_,
    _____X__, ________,
    _____X__, ________,
    ____XXXX, XXXX____,
    ____X___, ___X____,
    ___XX___, ___X____,
    __X_XXXX, XXXX____,
    _X__X___, ___X____,
    X___X___, ___X____,
    ____XXXX, XXXX____,
    ____X___, ___X____,
    ____X___, ___X____,
    ____X___, _X_X____,
    ____X___, __X_____
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_68C0[ 32] =   /* code 68C0 */
{
    ___X____, _X______,
    ___X____, _X______,
    ___X____, X_X_____,
    ___X____, X_X_____,
    XXXXXX_X, ___X____,
    ___X__X_, ____X___,
    __XX_X_X, XXXX_XX_,
    __XXX___, ________,
    _X_X_X__, X___X___,
    _X_X____, _X__X___,
    X__X__X_, _X__X___,
    ___X___X, _X_X____,
    ___X___X, ___X____,
    ___X____, __X_____,
    ___X_XXX, XXXXXXX_,
    ___X____, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6A21[ 32] =   /* code 6A21 */
{
    ___X___X, ___X____,
    ___X___X, ___X____,
    ___X_XXX, XXXXXX__,
    ___X___X, ___X____,
    XXXXXX__, ________,
    ___X__XX, XXXXX___,
    __XX__X_, ____X___,
    __XXX_XX, XXXXX___,
    _X_X_XX_, ____X___,
    _X_X__XX, XXXXX___,
    X__X____, _X______,
    ___X_XXX, XXXXXX__,
    ___X____, X_X_____,
    ___X___X, ___X____,
    ___X__X_, ____X___,
    ___X_X__, _____XX_
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6B4C[ 32] =   /* code 6B4C */
{
    ________, __X_____,
    XXXXXXXX, __X_____,
    ______X_, __X_____,
    _XXXX_X_, _XXXXXX_,
    _X__X_X_, _X____X_,
    _XXXX_X_, X____X__,
    ________, ___X____,
    XXXXXXXX, ___X____,
    ______X_, ___X____,
    _XXXX_X_, ___X____,
    _X__X_X_, __X_X___,
    _X__X_X_, __X_X___,
    _XXXX_X_, __X_X___,
    ______X_, _X___X__,
    ____X_X_, _X___X__,
    _____X__, X_____X_
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6CE5[ 32] =   /* code 6CE5 */
{
    ________, ________,
    __X___XX, XXXXXX__,
    ___X__X_, _____X__,
    ___X__X_, _____X__,
    X_____X_, _____X__,
    _X____XX, XXXXXX__,
    _X__X_X_, ________,
    ____X_X_, _X______,
    ___X__X_, _X___X__,
    ___X__X_, _X__X___,
    XXX___X_, _XXX____,
    __X___X_, _X______,
    __X__X__, _X____X_,
    __X__X__, _X____X_,
    __X_X___, __XXXXX_,
    ___X____, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6D4B[ 32] =   /* code 6D4B */
{
    ________, _____X__,
    __X__XXX, XX___X__,
    ___X_X__, _X___X__,
    ___X_X__, _X_X_X__,
    X____X_X, _X_X_X__,
    _X___X_X, _X_X_X__,
    _X___X_X, _X_X_X__,
    ___X_X_X, _X_X_X__,
    ___X_X_X, _X_X_X__,
    __X__X_X, _X_X_X__,
    XXX__X_X, _X_X_X__,
    __X____X, _____X__,
    __X___X_, X____X__,
    __X___X_, _X___X__,
    __X__X__, ___X_X__,
    ____X___, ____X___
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6D53[ 32] =   /* code 6D53 */
{
    ________, _X______,
    __X_____, _X______,
    ___X____, _X______,
    ___X_XXX, XXXXXX__,
    X____X__, X____X__,
    _X__X___, X___X___,
    _X_____X, _X______,
    ___X___X, _X___X__,
    ___X__XX, _X__X___,
    __X__X_X, __XX____,
    XXX_X__X, __X_____,
    __X____X, ___X____,
    __X____X, ____X___,
    __X____X, _X___X__,
    __X____X, X_____X_,
    _______X, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6E29[ 32] =   /* code 6E29 */
{
    ________, ________,
    __X___XX, XXXXX___,
    ___X__X_, ____X___,
    ___X__X_, ____X___,
    X_____XX, XXXXX___,
    _X____X_, ____X___,
    _X____X_, ____X___,
    ___X__XX, XXXXX___,
    ___X____, ________,
    __X__XXX, XXXXXX__,
    XXX__X__, X_X__X__,
    __X__X__, X_X__X__,
    __X__X__, X_X__X__,
    __X__X__, X_X__X__,
    __X_XXXX, XXXXXXX_,
    ________, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6E7F[ 32] =   /* code 6E7F */
{
    ________, ________,
    __X__XXX, XXXXX___,
    ___X_X__, ____X___,
    ___X_X__, ____X___,
    X____XXX, XXXXX___,
    _X___X__, ____X___,
    _X___X__, ____X___,
    ___X_XXX, XXXXX___,
    ___X___X, __X_____,
    __X____X, __X_____,
    XXX_X__X, __X__X__,
    __X__X_X, __X_X___,
    __X___XX, __XX____,
    __X____X, __X_____,
    __X_XXXX, XXXXXXX_,
    ________, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_73AF[ 32] =   /* code 73AF */
{
    ________, ________,
    ________, ________,
    XXXXXX_X, XXXXXXX_,
    ___X____, ___X____,
    ___X____, ___X____,
    ___X____, __X_____,
    ___X____, __X_____,
    _XXXXX__, _XX_X___,
    ___X____, X_X__X__,
    ___X___X, __X___X_,
    ___X__X_, __X___X_,
    ___X____, __X_____,
    ___XXX__, __X_____,
    XXX_____, __X_____,
    _X______, __X_____,
    ________, __X_____
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_754C[ 32] =   /* code 754C */
{
    ________, ________,
    ___XXXXX, XXXX____,
    ___X___X, ___X____,
    ___X___X, ___X____,
    ___XXXXX, XXXX____,
    ___X___X, ___X____,
    ___X___X, ___X____,
    ___XXXXX, XXXX____,
    ______X_, X_______,
    ____XX__, _XX_____,
    __XX_X__, _X_XX___,
    XX___X__, _X___XX_,
    _____X__, _X______,
    ____X___, _X______,
    ____X___, _X______,
    ___X____, _X______
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_7761[ 32] =   /* code 7761 */
{
    ________, ___X____,
    ________, _XXXX___,
    XXXX__XX, XX______,
    X__X____, _X______,
    X__X____, _X______,
    XXXX_XXX, XXXXXX__,
    X__X__X_, _X__X___,
    X__X__X_, _X__X___,
    XXXX_XXX, XXXXXXX_,
    X__X__X_, _X__X___,
    X__X__X_, _X__X___,
    X__X_XXX, XXXXXX__,
    XXXX____, _X______,
    X__X____, _X______,
    _____XXX, XXXXXX__,
    ________, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_7BEE[ 32] =   /* code 7BEE */
{
    __X_____, _X______,
    __XXXXXX, _XXXXXX_,
    _X__X___, X__X____,
    X____X_X, ____X___,
    _____X__, X_______,
    __X__X__, X_______,
    __X__X__, XXXXXX__,
    __X__X__, X_X_____,
    __X__X_X, ___X____,
    ________, ________,
    __XXXXXX, XXXXX___,
    __X__X__, _X__X___,
    __X__X__, _X__X___,
    __X__X__, _X__X___,
    XXXXXXXX, XXXXXXX_,
    ________, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_88AB[ 32] =   /* code 88AB */
{
    __X_____, ___X____,
    ___X____, ___X____,
    ________, ___X____,
    XXXXX__X, XXXXXXX_,
    ____X__X, ___X__X_,
    ___X___X, ___X_X__,
    ___X_X_X, ___X____,
    __XXX__X, XXXXXX__,
    _X_X_X_X, _X___X__,
    X__X___X, _X___X__,
    ___X___X, __X_X___,
    ___X___X, __X_X___,
    ___X___X, ___X____,
    ___X__X_, __X_X___,
    ___X__X_, _X___X__,
    ___X_X__, X_____X_
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_8BBE[ 32] =   /* code 8BBE */
{
    ________, ________,
    __X____X, XXXX____,
    ___X___X, ___X____,
    ___X___X, ___X____,
    _______X, ___X____,
    ______X_, ____XXX_,
    XXXX_X__, ________,
    ___X__XX, XXXXX___,
    ___X___X, ____X___,
    ___X___X, ___X____,
    ___X____, X__X____,
    ___X_X__, X_X_____,
    ___XX___, _X______,
    ___X____, X_X_____,
    ______XX, ___XX___,
    ____XX__, _____XX_
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_8F66[ 32] =   /* code 8F66 */
{
    ______X_, ________,
    ______X_, ________,
    ______X_, ________,
    _XXXXXXX, XXXXXX__,
    _____X__, ________,
    ____X__X, ________,
    ___X___X, ________,
    __X____X, ________,
    __XXXXXX, XXXXX___,
    _______X, ________,
    _______X, ________,
    XXXXXXXX, XXXXXXX_,
    _______X, ________,
    _______X, ________,
    _______X, ________,
    _______X, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_9192[ 32] =   /* code 9192 */
{
    ________, ________,
    XXXXXXX_, _XXXXX__,
    __X_X___, _X___X__,
    __X_X___, _XXXXX__,
    XXXXXXX_, _X___X__,
    X_X_X_X_, _XXXXX__,
    X_X_X_X_, ___X____,
    X_X_X_X_, _X_X____,
    X_X_XXX_, _XXXXX__,
    XX____X_, X__X____,
    X_____X_, ___X____,
    XXXXXXX_, _XXXXX__,
    X_____X_, ___X____,
    X_____X_, ___X____,
    XXXXXXX_, XXXXXXX_,
    X_____X_, ________
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_9632[ 32] =   /* code 9632 */
{
    ________, _X______,
    _XXXXX__, __X_____,
    _X___X__, __X_____,
    _X__X_XX, XXXXXXX_,
    _X__X___, X_______,
    _X_X____, X_______,
    _X__X___, X_______,
    _X__X___, XXXXXX__,
    _X___X__, X____X__,
    _X___X__, X____X__,
    _X___X__, X____X__,
    _XX_X___, X____X__,
    _X_X___X, _____X__,
    _X_____X, _____X__,
    _X____X_, __X_X___,
    _X___X__, ___X____
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_9762[ 32] =   /* code 9762 */
{
    ________, ________,
    XXXXXXXX, XXXXXXX_,
    ______X_, ________,
    ______X_, ________,
    _____X__, ________,
    __XXXXXX, XXXXX___,
    __X__X__, _X__X___,
    __X__X__, _X__X___,
    __X__XXX, XX__X___,
    __X__X__, _X__X___,
    __X__X__, _X__X___,
    __X__XXX, XX__X___,
    __X__X__, _X__X___,
    __X__X__, _X__X___,
    __XXXXXX, XXXXX___,
    __X_____, ____X___
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_97F3[ 32] =   /* code 97F3 */
{
    ______X_, ________,
    _______X, ________,
    __XXXXXX, XXXXX___,
    ________, ________,
    ____X___, __X_____,
    _____X__, _X______,
    XXXXXXXX, XXXXXXX_,
    ________, ________,
    ___XXXXX, XXXX____,
    ___X____, ___X____,
    ___X____, ___X____,
    ___XXXXX, XXXX____,
    ___X____, ___X____,
    ___X____, ___X____,
    ___XXXXX, XXXX____,
    ___X____, ___X____
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_9875[ 32] =   /* code 9875 */
{
    ________, ________,
    _XXXXXXX, XXXXXX__,
    ______X_, ________,
    _____X__, ________,
    ___XXXXX, XXXX____,
    ___X____, ___X____,
    ___X___X, ___X____,
    ___X___X, ___X____,
    ___X___X, ___X____,
    ___X___X, ___X____,
    ___X___X, ___X____,
    ___X__X_, X__X____,
    ______X_, _X______,
    _____X__, __X_____,
    ___XX___, ___X____,
    _XX_____, ____X___
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_9CC5[ 32] =   /* code 9CC5 */
{
    _X______, ____X___,
    _X______, XX__X___,
    _XXXX_XX, ____X___,
    X___X__X, ____X___,
    ___X___X, __X_X_X_,
    XXXXX__X, __X_X_X_,
    X_X_X_XX, X_X_XX__,
    X_X_X__X, _X__X___,
    XXXXX__X, ____X___,
    X_X_X_XX, X___X___,
    X_X_XX_X, _X_X_X__,
    XXXXX__X, ___X_X__,
    _______X, ___X_X__,
    ___XX__X, __X__X__,
    XXX____X, __X__X__,
    _X_____X, _X____X_
};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_9E2D[ 32] =   /* code 9E2D */
{
    ________, __X_____,
    XXXXXXX_, _X______,
    X__X__X_, XXXXXX__,
    X__X__X_, X____X__,
    X__X__X_, X_X__X__,
    XXXXXXX_, X____X__,
    X__X__X_, X__X_X__,
    X__X__X_, X___X___,
    X__X__X_, X_______,
    XXXXXXX_, XXXXXXX_,
    X__X__X_, ______X_,
    ___X____, ______X_,
    ___X___X, XXXXX_X_,
    ___X____, ______X_,
    ___X____, ___X_X__,
    ___X____, ____X___
};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontsong16_CharInfo[73] =
{
    {   8,   8,  1, acGUI_Fontsong16_0043 } /* code 0043 */
    , {   8,   8,  1, acGUI_Fontsong16_004F } /* code 004F */
    , {  16,  16,  2, acGUI_Fontsong16_2103 } /* code 2103 */
    , {  16,  16,  2, acGUI_Fontsong16_4E00 } /* code 4E00 */
    , {  16,  16,  2, acGUI_Fontsong16_4E0A } /* code 4E0A */
    , {  16,  16,  2, acGUI_Fontsong16_4E0B } /* code 4E0B */
    , {  16,  16,  2, acGUI_Fontsong16_4E16 } /* code 4E16 */
    , {  16,  16,  2, acGUI_Fontsong16_4E3B } /* code 4E3B */
    , {  16,  16,  2, acGUI_Fontsong16_4E50 } /* code 4E50 */
    , {  16,  16,  2, acGUI_Fontsong16_4E56 } /* code 4E56 */
    , {  16,  16,  2, acGUI_Fontsong16_4F53 } /* code 4F53 */
    , {  16,  16,  2, acGUI_Fontsong16_5077 } /* code 5077 */
    , {  16,  16,  2, acGUI_Fontsong16_513F } /* code 513F */
    , {  16,  16,  2, acGUI_Fontsong16_5154 } /* code 5154 */
    , {  16,  16,  2, acGUI_Fontsong16_5168 } /* code 5168 */
    , {  16,  16,  2, acGUI_Fontsong16_5173 } /* code 5173 */
    , {  16,  16,  2, acGUI_Fontsong16_51C0 } /* code 51C0 */
    , {  16,  16,  2, acGUI_Fontsong16_5236 } /* code 5236 */
    , {  16,  16,  2, acGUI_Fontsong16_52A0 } /* code 52A0 */
    , {  16,  16,  2, acGUI_Fontsong16_5316 } /* code 5316 */
    , {  16,  16,  2, acGUI_Fontsong16_53C2 } /* code 53C2 */
    , {  16,  16,  2, acGUI_Fontsong16_53EA } /* code 53EA */
    , {  16,  16,  2, acGUI_Fontsong16_5410 } /* code 5410 */
    , {  16,  16,  2, acGUI_Fontsong16_5426 } /* code 5426 */
    , {  16,  16,  2, acGUI_Fontsong16_5668 } /* code 5668 */
    , {  16,  16,  2, acGUI_Fontsong16_5728 } /* code 5728 */
    , {  16,  16,  2, acGUI_Fontsong16_5883 } /* code 5883 */
    , {  16,  16,  2, acGUI_Fontsong16_5907 } /* code 5907 */
    , {  16,  16,  2, acGUI_Fontsong16_5976 } /* code 5976 */
    , {  16,  16,  2, acGUI_Fontsong16_597D } /* code 597D */
    , {  16,  16,  2, acGUI_Fontsong16_5988 } /* code 5988 */
    , {  16,  16,  2, acGUI_Fontsong16_5A74 } /* code 5A74 */
    , {  16,  16,  2, acGUI_Fontsong16_5B50 } /* code 5B50 */
    , {  16,  16,  2, acGUI_Fontsong16_5B66 } /* code 5B66 */
    , {  16,  16,  2, acGUI_Fontsong16_5B89 } /* code 5B89 */
    , {  16,  16,  2, acGUI_Fontsong16_5C0F } /* code 5C0F */
    , {  16,  16,  2, acGUI_Fontsong16_5C3F } /* code 5C3F */
    , {  16,  16,  2, acGUI_Fontsong16_5E8A } /* code 5E8A */
    , {  16,  16,  2, acGUI_Fontsong16_5EA6 } /* code 5EA6 */
    , {  16,  16,  2, acGUI_Fontsong16_5F00 } /* code 5F00 */
    , {  16,  16,  2, acGUI_Fontsong16_5F0F } /* code 5F0F */
    , {  16,  16,  2, acGUI_Fontsong16_6293 } /* code 6293 */
    , {  16,  16,  2, acGUI_Fontsong16_6342 } /* code 6342 */
    , {  16,  16,  2, acGUI_Fontsong16_63A7 } /* code 63A7 */
    , {  16,  16,  2, acGUI_Fontsong16_6446 } /* code 6446 */
    , {  16,  16,  2, acGUI_Fontsong16_6447 } /* code 6447 */
    , {  16,  16,  2, acGUI_Fontsong16_6570 } /* code 6570 */
    , {  16,  16,  2, acGUI_Fontsong16_662F } /* code 662F */
    , {  16,  16,  2, acGUI_Fontsong16_6696 } /* code 6696 */
    , {  16,  16,  2, acGUI_Fontsong16_66F2 } /* code 66F2 */
    , {  16,  16,  2, acGUI_Fontsong16_6709 } /* code 6709 */
    , {  16,  16,  2, acGUI_Fontsong16_68C0 } /* code 68C0 */
    , {  16,  16,  2, acGUI_Fontsong16_6A21 } /* code 6A21 */
    , {  16,  16,  2, acGUI_Fontsong16_6B4C } /* code 6B4C */
    , {  16,  16,  2, acGUI_Fontsong16_6CE5 } /* code 6CE5 */
    , {  16,  16,  2, acGUI_Fontsong16_6D4B } /* code 6D4B */
    , {  16,  16,  2, acGUI_Fontsong16_6D53 } /* code 6D53 */
    , {  16,  16,  2, acGUI_Fontsong16_6E29 } /* code 6E29 */
    , {  16,  16,  2, acGUI_Fontsong16_6E7F } /* code 6E7F */
    , {  16,  16,  2, acGUI_Fontsong16_73AF } /* code 73AF */
    , {  16,  16,  2, acGUI_Fontsong16_754C } /* code 754C */
    , {  16,  16,  2, acGUI_Fontsong16_7761 } /* code 7761 */
    , {  16,  16,  2, acGUI_Fontsong16_7BEE } /* code 7BEE */
    , {  16,  16,  2, acGUI_Fontsong16_88AB } /* code 88AB */
    , {  16,  16,  2, acGUI_Fontsong16_8BBE } /* code 8BBE */
    , {  16,  16,  2, acGUI_Fontsong16_8F66 } /* code 8F66 */
    , {  16,  16,  2, acGUI_Fontsong16_9192 } /* code 9192 */
    , {  16,  16,  2, acGUI_Fontsong16_9632 } /* code 9632 */
    , {  16,  16,  2, acGUI_Fontsong16_9762 } /* code 9762 */
    , {  16,  16,  2, acGUI_Fontsong16_97F3 } /* code 97F3 */
    , {  16,  16,  2, acGUI_Fontsong16_9875 } /* code 9875 */
    , {  16,  16,  2, acGUI_Fontsong16_9CC5 } /* code 9CC5 */
    , {  16,  16,  2, acGUI_Fontsong16_9E2D } /* code 9E2D */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop71 =
{
    0x9E2D /* first character */
    , 0x9E2D /* last character  */
    , &GUI_Fontsong16_CharInfo[ 72] /* address of first character */
    , (GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop70 =
{
    0x9CC5 /* first character */
    , 0x9CC5 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 71] /* address of first character */
    , &GUI_Fontsong16_Prop71 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop69 =
{
    0x9875 /* first character */
    , 0x9875 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 70] /* address of first character */
    , &GUI_Fontsong16_Prop70 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop68 =
{
    0x97F3 /* first character */
    , 0x97F3 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 69] /* address of first character */
    , &GUI_Fontsong16_Prop69 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop67 =
{
    0x9762 /* first character */
    , 0x9762 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 68] /* address of first character */
    , &GUI_Fontsong16_Prop68 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop66 =
{
    0x9632 /* first character */
    , 0x9632 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 67] /* address of first character */
    , &GUI_Fontsong16_Prop67 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop65 =
{
    0x9192 /* first character */
    , 0x9192 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 66] /* address of first character */
    , &GUI_Fontsong16_Prop66 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop64 =
{
    0x8F66 /* first character */
    , 0x8F66 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 65] /* address of first character */
    , &GUI_Fontsong16_Prop65 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop63 =
{
    0x8BBE /* first character */
    , 0x8BBE /* last character  */
    , &GUI_Fontsong16_CharInfo[ 64] /* address of first character */
    , &GUI_Fontsong16_Prop64 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop62 =
{
    0x88AB /* first character */
    , 0x88AB /* last character  */
    , &GUI_Fontsong16_CharInfo[ 63] /* address of first character */
    , &GUI_Fontsong16_Prop63 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop61 =
{
    0x7BEE /* first character */
    , 0x7BEE /* last character  */
    , &GUI_Fontsong16_CharInfo[ 62] /* address of first character */
    , &GUI_Fontsong16_Prop62 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop60 =
{
    0x7761 /* first character */
    , 0x7761 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 61] /* address of first character */
    , &GUI_Fontsong16_Prop61 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop59 =
{
    0x754C /* first character */
    , 0x754C /* last character  */
    , &GUI_Fontsong16_CharInfo[ 60] /* address of first character */
    , &GUI_Fontsong16_Prop60 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop58 =
{
    0x73AF /* first character */
    , 0x73AF /* last character  */
    , &GUI_Fontsong16_CharInfo[ 59] /* address of first character */
    , &GUI_Fontsong16_Prop59 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop57 =
{
    0x6E7F /* first character */
    , 0x6E7F /* last character  */
    , &GUI_Fontsong16_CharInfo[ 58] /* address of first character */
    , &GUI_Fontsong16_Prop58 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop56 =
{
    0x6E29 /* first character */
    , 0x6E29 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 57] /* address of first character */
    , &GUI_Fontsong16_Prop57 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop55 =
{
    0x6D53 /* first character */
    , 0x6D53 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 56] /* address of first character */
    , &GUI_Fontsong16_Prop56 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop54 =
{
    0x6D4B /* first character */
    , 0x6D4B /* last character  */
    , &GUI_Fontsong16_CharInfo[ 55] /* address of first character */
    , &GUI_Fontsong16_Prop55 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop53 =
{
    0x6CE5 /* first character */
    , 0x6CE5 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 54] /* address of first character */
    , &GUI_Fontsong16_Prop54 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop52 =
{
    0x6B4C /* first character */
    , 0x6B4C /* last character  */
    , &GUI_Fontsong16_CharInfo[ 53] /* address of first character */
    , &GUI_Fontsong16_Prop53 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop51 =
{
    0x6A21 /* first character */
    , 0x6A21 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 52] /* address of first character */
    , &GUI_Fontsong16_Prop52 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop50 =
{
    0x68C0 /* first character */
    , 0x68C0 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 51] /* address of first character */
    , &GUI_Fontsong16_Prop51 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop49 =
{
    0x6709 /* first character */
    , 0x6709 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 50] /* address of first character */
    , &GUI_Fontsong16_Prop50 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop48 =
{
    0x66F2 /* first character */
    , 0x66F2 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 49] /* address of first character */
    , &GUI_Fontsong16_Prop49 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop47 =
{
    0x6696 /* first character */
    , 0x6696 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 48] /* address of first character */
    , &GUI_Fontsong16_Prop48 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop46 =
{
    0x662F /* first character */
    , 0x662F /* last character  */
    , &GUI_Fontsong16_CharInfo[ 47] /* address of first character */
    , &GUI_Fontsong16_Prop47 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop45 =
{
    0x6570 /* first character */
    , 0x6570 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 46] /* address of first character */
    , &GUI_Fontsong16_Prop46 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop44 =
{
    0x6446 /* first character */
    , 0x6447 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 44] /* address of first character */
    , &GUI_Fontsong16_Prop45 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop43 =
{
    0x63A7 /* first character */
    , 0x63A7 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 43] /* address of first character */
    , &GUI_Fontsong16_Prop44 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop42 =
{
    0x6342 /* first character */
    , 0x6342 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 42] /* address of first character */
    , &GUI_Fontsong16_Prop43 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop41 =
{
    0x6293 /* first character */
    , 0x6293 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 41] /* address of first character */
    , &GUI_Fontsong16_Prop42 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop40 =
{
    0x5F0F /* first character */
    , 0x5F0F /* last character  */
    , &GUI_Fontsong16_CharInfo[ 40] /* address of first character */
    , &GUI_Fontsong16_Prop41 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop39 =
{
    0x5F00 /* first character */
    , 0x5F00 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 39] /* address of first character */
    , &GUI_Fontsong16_Prop40 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop38 =
{
    0x5EA6 /* first character */
    , 0x5EA6 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 38] /* address of first character */
    , &GUI_Fontsong16_Prop39 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop37 =
{
    0x5E8A /* first character */
    , 0x5E8A /* last character  */
    , &GUI_Fontsong16_CharInfo[ 37] /* address of first character */
    , &GUI_Fontsong16_Prop38 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop36 =
{
    0x5C3F /* first character */
    , 0x5C3F /* last character  */
    , &GUI_Fontsong16_CharInfo[ 36] /* address of first character */
    , &GUI_Fontsong16_Prop37 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop35 =
{
    0x5C0F /* first character */
    , 0x5C0F /* last character  */
    , &GUI_Fontsong16_CharInfo[ 35] /* address of first character */
    , &GUI_Fontsong16_Prop36 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop34 =
{
    0x5B89 /* first character */
    , 0x5B89 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 34] /* address of first character */
    , &GUI_Fontsong16_Prop35 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop33 =
{
    0x5B66 /* first character */
    , 0x5B66 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 33] /* address of first character */
    , &GUI_Fontsong16_Prop34 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop32 =
{
    0x5B50 /* first character */
    , 0x5B50 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 32] /* address of first character */
    , &GUI_Fontsong16_Prop33 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop31 =
{
    0x5A74 /* first character */
    , 0x5A74 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 31] /* address of first character */
    , &GUI_Fontsong16_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop30 =
{
    0x5988 /* first character */
    , 0x5988 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 30] /* address of first character */
    , &GUI_Fontsong16_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop29 =
{
    0x597D /* first character */
    , 0x597D /* last character  */
    , &GUI_Fontsong16_CharInfo[ 29] /* address of first character */
    , &GUI_Fontsong16_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop28 =
{
    0x5976 /* first character */
    , 0x5976 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 28] /* address of first character */
    , &GUI_Fontsong16_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop27 =
{
    0x5907 /* first character */
    , 0x5907 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 27] /* address of first character */
    , &GUI_Fontsong16_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop26 =
{
    0x5883 /* first character */
    , 0x5883 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 26] /* address of first character */
    , &GUI_Fontsong16_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop25 =
{
    0x5728 /* first character */
    , 0x5728 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 25] /* address of first character */
    , &GUI_Fontsong16_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop24 =
{
    0x5668 /* first character */
    , 0x5668 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 24] /* address of first character */
    , &GUI_Fontsong16_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop23 =
{
    0x5426 /* first character */
    , 0x5426 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 23] /* address of first character */
    , &GUI_Fontsong16_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop22 =
{
    0x5410 /* first character */
    , 0x5410 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 22] /* address of first character */
    , &GUI_Fontsong16_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop21 =
{
    0x53EA /* first character */
    , 0x53EA /* last character  */
    , &GUI_Fontsong16_CharInfo[ 21] /* address of first character */
    , &GUI_Fontsong16_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop20 =
{
    0x53C2 /* first character */
    , 0x53C2 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 20] /* address of first character */
    , &GUI_Fontsong16_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop19 =
{
    0x5316 /* first character */
    , 0x5316 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 19] /* address of first character */
    , &GUI_Fontsong16_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop18 =
{
    0x52A0 /* first character */
    , 0x52A0 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 18] /* address of first character */
    , &GUI_Fontsong16_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop17 =
{
    0x5236 /* first character */
    , 0x5236 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 17] /* address of first character */
    , &GUI_Fontsong16_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop16 =
{
    0x51C0 /* first character */
    , 0x51C0 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 16] /* address of first character */
    , &GUI_Fontsong16_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop15 =
{
    0x5173 /* first character */
    , 0x5173 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 15] /* address of first character */
    , &GUI_Fontsong16_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop14 =
{
    0x5168 /* first character */
    , 0x5168 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 14] /* address of first character */
    , &GUI_Fontsong16_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop13 =
{
    0x5154 /* first character */
    , 0x5154 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 13] /* address of first character */
    , &GUI_Fontsong16_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop12 =
{
    0x513F /* first character */
    , 0x513F /* last character  */
    , &GUI_Fontsong16_CharInfo[ 12] /* address of first character */
    , &GUI_Fontsong16_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop11 =
{
    0x5077 /* first character */
    , 0x5077 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 11] /* address of first character */
    , &GUI_Fontsong16_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop10 =
{
    0x4F53 /* first character */
    , 0x4F53 /* last character  */
    , &GUI_Fontsong16_CharInfo[ 10] /* address of first character */
    , &GUI_Fontsong16_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop9 =
{
    0x4E56 /* first character */
    , 0x4E56 /* last character  */
    , &GUI_Fontsong16_CharInfo[  9] /* address of first character */
    , &GUI_Fontsong16_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop8 =
{
    0x4E50 /* first character */
    , 0x4E50 /* last character  */
    , &GUI_Fontsong16_CharInfo[  8] /* address of first character */
    , &GUI_Fontsong16_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop7 =
{
    0x4E3B /* first character */
    , 0x4E3B /* last character  */
    , &GUI_Fontsong16_CharInfo[  7] /* address of first character */
    , &GUI_Fontsong16_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop6 =
{
    0x4E16 /* first character */
    , 0x4E16 /* last character  */
    , &GUI_Fontsong16_CharInfo[  6] /* address of first character */
    , &GUI_Fontsong16_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop5 =
{
    0x4E0A /* first character */
    , 0x4E0B /* last character  */
    , &GUI_Fontsong16_CharInfo[  4] /* address of first character */
    , &GUI_Fontsong16_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop4 =
{
    0x4E00 /* first character */
    , 0x4E00 /* last character  */
    , &GUI_Fontsong16_CharInfo[  3] /* address of first character */
    , &GUI_Fontsong16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop3 =
{
    0x2103 /* first character */
    , 0x2103 /* last character  */
    , &GUI_Fontsong16_CharInfo[  2] /* address of first character */
    , &GUI_Fontsong16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop2 =
{
    0x004F /* first character */
    , 0x004F /* last character  */
    , &GUI_Fontsong16_CharInfo[  1] /* address of first character */
    , &GUI_Fontsong16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop1 =
{
    0x0043 /* first character */
    , 0x0043 /* last character  */
    , &GUI_Fontsong16_CharInfo[  0] /* address of first character */
    , &GUI_Fontsong16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontsong16 =
{
    GUI_FONTTYPE_PROP /* type of font    */
    , 16 /* height of font  */
    , 16 /* space of font y */
    , 1 /* magnification x */
    , 1 /* magnification y */
    , {&GUI_Fontsong16_Prop1}
    , 14 /* Baseline */
    , 7 /* Height of lowercase characters */
    , 11 /* Height of capital characters */
};

