/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug  8 2014, 14:49:54                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "led.h"
#include "WindowDLG.h"

int g_year, g_month, g_day, g_hour, g_minute; //网络时间
WM_HWIN g_time_win; //时间窗口句柄
WM_HWIN g_main_win; //1主界面窗口句柄
WM_HWIN g_environment_win; //2环境界面窗口句柄
WM_HWIN g_equipment_win; //3设备模块窗口句柄
WM_HWIN g_baby_detection_win;//4下一页
char valuemlx90614[7];
char valuedht11_tempe[7];
char valuedht11_humidity[7];
char valuemq_7[7];
char valuerain_water[7];
void Time_Init(void)
{
    g_year = 2022;
    g_month = 5;
    g_day = 6;
    g_hour = 7;
    g_minute = 8;
}

//背景窗口回调函数，WM的裁剪机制确保了仅重绘无效区域，并不是完全的执行下面的语句！！！！
static void _cbBkWindow(WM_MESSAGE *pMsg)
{
    //根据不同的消息类型处理
    switch (pMsg->MsgId)
    {
    //WM_PAINT消息，窗口重绘自身
    case WM_PAINT:
        //为当前窗口填充背景
        GUI_SetBkColor(GUI_BLACK);
        GUI_Clear();
        break;
    default:
        //此函数可处理未处理的消息
        WM_DefaultProc(pMsg);
        break;
    }
}

//窗口回调函数
static void _cbWindow(WM_MESSAGE *pMsg)
{
    GUI_RECT Rect;
    if (wifi_flag == 1)
    {
        GUI_DrawBitmap(&bmwifi, 3, 1);
    }
    else
    {
        GUI_DrawBitmap(&bmnowifi, 3, 1);
    }
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        WM_GetInsideRect(&Rect);                //返回活动窗口减去边界后的尺寸,即客户区坐标
        GUI_SetBkColor(GUI_WHITE);              //背景色
        GUI_SetColor(GUI_LIGHTBLUE);
        GUI_ClearRectEx(&Rect);                 //清除Rect区域,既绘制背景
        GUI_DrawRectEx(&Rect);                  //绘制Rect区域,既绘制框框
        GUI_SetTextMode(GUI_TEXTMODE_TRANS);    //透明文本模式
        GUI_SetColor(GUI_BLUE);                 //字体颜色
        GUI_SetFont(&GUI_Font24_ASCII);         //设置字体
        GUI_DispDecAt(g_year, 60, 2, 4);          //显示年
        GUI_DispCharAt(47, 108, 2);             //显示 /
        GUI_DispDecAt(g_month, 116, 2, 2);        //显示月
        GUI_DispCharAt(47, 140, 2);             //显示 /
        GUI_DispDecAt(g_day, 148, 2, 2);          //显示日
        GUI_DispCharAt(32, 172, 2);             //显示空格
        GUI_DispDecAt(g_hour, 180, 2, 2);         //显示时
        GUI_DispCharAt(58, 204, 2);             //显示冒号
        GUI_DispDecAt(g_minute, 212, 2, 2);       //显示分
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

void CreateWindowTime(void)
{
    Time_Init();
    WM_SetCallback(WM_HBKWIN, _cbBkWindow); //设置背景桌面的回调函数
    //创建前景窗口，尺寸150*100
    g_time_win = WM_CreateWindow(0, 0, 240, 27, WM_CF_SHOW | WM_CF_MEMDEV, _cbWindow, 0); //WM_CF_SHOW创建后显示
}

/*********************************************************************
*
*       _aDialogCreate1
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate1[] =
{
    { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 27, 240, 293, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "环境参数", ID_BUTTON_0, 17, 260, 74, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "设备控制", ID_BUTTON_1, 144, 260, 74, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "体温开关", ID_BUTTON_2, 170, 193, 74, 30, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "体温开关", ID_TEXT_0, 60, 195, 90, 33, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "婴儿体温", ID_TEXT_1, 60, 225, 90, 33, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "℃", ID_TEXT_8, 210, 228, 20, 30, 0, 0x0, 0 },

};

/*********************************************************************
*
*      111111111111111111111111111111111111111111111111111111111111
*/
static void _cbDialog1(WM_MESSAGE *pMsg)
{
    // const void * pData;
    WM_HWIN      hItem;
    int          NCode;
    int          Id;
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        GUI_SetBkColor(GUI_DARKSLATEGRAY);//GUI_MYWIN1
        GUI_Clear();
        GUI_SetFont(&GUI_Font16_ASCII);             //设置字体X
        GUI_DrawBitmap(&bmtitle, 0, 0);
        GUI_DrawBitmap(&bmbaby, 40, 80);
        GUI_DrawBitmap(&bmbabytemperature, 10, 220);
        // GUI_DrawBitmap(&bmwakeup, 10, 170);
        GUI_DispStringAt(valuemlx90614, 180, 235); //体温
        WM_HideWindow(g_environment_win); //隐藏Page1
        WM_HideWindow(g_equipment_win); //隐藏Page2
        WM_HideWindow(g_baby_detection_win);//隐藏Page3
        break;
    case WM_INIT_DIALOG:
        GUI_UC_SetEncodeUTF8();
        //初始化16字体大小的文字
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe4\xbd\x93\xe6\xb8\xa9\xe5\xbc\x80\xe5\x85\xb3");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe5\xa9\xb4\xe5\x84\xbf\xe4\xbd\x93\xe6\xb8\xa9");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe2\x84\x83");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
        BUTTON_SetFont(hItem, &GUI_Fontsong16);//song16
        BUTTON_SetText(hItem, "\xe7\x8e\xaf\xe5\xa2\x83\xe5\x8f\x82\xe6\x95\xb0");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
        BUTTON_SetFont(hItem, &GUI_Fontsong16);//song16
        BUTTON_SetText(hItem, "\xe8\xae\xbe\xe5\xa4\x87\xe6\x8e\xa7\xe5\x88\xb6");
        //     hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
        BUTTON_SetBitmapEx(hItem, 0, &bmoff, 0, 0);
        BUTTON_SetText(hItem, "");  //在按钮上显示空
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
        //
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id)
        {
        case ID_BUTTON_0: // Notifications sent by 'Button' 环境参数按键
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            case WM_NOTIFICATION_RELEASED:
                WM_HideWindow(g_main_win); //隐藏Page0
                WM_HideWindow(g_equipment_win); //隐藏Page0
                WM_ShowWindow(g_environment_win);//显示Page1
                WM_HideWindow(g_baby_detection_win);//显示Page1
                // USER END
                break;
            }
            break;
        case ID_BUTTON_1: // Notifications sent by 'Button'  设备控制按键
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            case WM_NOTIFICATION_RELEASED:
                WM_HideWindow(g_main_win); //隐藏Page0
                WM_HideWindow(g_environment_win); //隐藏Page0
                WM_HideWindow(g_baby_detection_win);
                WM_ShowWindow(g_equipment_win);//显示Page
                break;
                // USER END
            }
            break;
        case ID_BUTTON_2: // Notifications sent by 'Button'  体温开关按键
            hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);  //获得按钮句柄!!!
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                /*更改皮肤*/
                BUTTON_SetBitmapEx(hItem, 0, app_control_mcu.valuetemp_check ? &bmoff : &bmon, 0, 0);
                ///*标志位取反*/
                app_control_mcu.valuetemp_check = !app_control_mcu.valuetemp_check;
                ///*更改APP*/
                currentDataPoint.valuetemp_check = app_control_mcu.valuetemp_check;
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        }
        break;
    // USER START (Optionally insert additional message handling)
    // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate2[] =
{
    { WINDOW_CreateIndirect, "Window", ID_WINDOW_1, 1, 0, 240, 320, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "环境温度", ID_TEXT_2, 60, 80, 100, 30, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "环境湿度", ID_TEXT_3, 60, 130, 100, 30, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "CO浓度", ID_TEXT_4, 60, 180, 100, 30, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "尿床", ID_TEXT_6, 60, 230, 100, 30, 0, 0x0, 0 },
    { EDIT_CreateIndirect, "尿床是否", ID_EDIT_23, 180, 230, 30, 30, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "℃", ID_TEXT_8, 210, 80, 20, 30, 0, 0x0, 0 },
		//{ TEXT_CreateIndirect, "婴儿体温", ID_TEXT_1, 60, 215, 90, 33, 0, 0x0, 0 },
    //{ TEXT_CreateIndirect, "℃", ID_TEXT_16, 210, 215, 20, 30, 0, 0x0, 0 },

    { BUTTON_CreateIndirect, "主界面", ID_BUTTON_5, 20, 290, 74, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "设备控制", ID_BUTTON_6, 150, 290, 74, 30, 0, 0x0, 0 },

};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       22222222222222222222222222222222222222222222222222222222
*/
static void _cbDialog2(WM_MESSAGE *pMsg)
{
    WM_HWIN      hItem;
    int NCode;
    int Id;
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        GUI_SetBkColor(GUI_DARKSLATEGRAY);//GUI_MYWIN1
        GUI_Clear();
        GUI_DrawBitmap(&bmbed, 10, 230);
        GUI_DrawBitmap(&bmenv, 0, 0);
        GUI_DrawBitmap(&bmenvironmenttemperature, 10, 80);
        GUI_DrawBitmap(&bmenvironmenthumidity, 10, 130);
        GUI_DrawBitmap(&bmsmoke, 10, 180);
        GUI_SetFont(&GUI_Font16_ASCII);             //设置字体X
        GUI_DispStringAt(valuedht11_tempe, 170, 80);
        GUI_DispStringAt(valuedht11_humidity, 170, 135);
        GUI_DispStringAt("%RH", 205, 135);
        GUI_DispStringAt(valuemq_7, 170, 180);
        GUI_DispStringAt("PPM", 205, 180);

//				GUI_DrawBitmap(&bmbabytemperature, 10, 215);
//        // GUI_DrawBitmap(&bmwakeup, 10, 170);
//        GUI_DispStringAt("36.9", 180, 220); //体温

        if (g_warn_rain_water==1)                    //尿床
        {
            hItem = pMsg->hWin;
            WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
            hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_23);
            EDIT_SetBkColor(hItem, 1, GUI_YELLOW);
            EDIT_SetFont(hItem, &GUI_Fontsong22);//song16
            EDIT_SetTextColor(hItem, 1, GUI_RED);
            EDIT_SetText(hItem, " \xe6\x98\xaf");  //在按钮上显示空
        }
        else
        {
            hItem = pMsg->hWin;
            WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
            hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_23);
            EDIT_SetBkColor(hItem, 1, GUI_WHITE);
            EDIT_SetFont(hItem, &GUI_Fontsong22);//song16
            EDIT_SetTextColor(hItem, 1, GUI_BLACK);
            EDIT_SetText(hItem, "\xe5\x90\xa6");  //在按钮上显示空
        }
        break;
    case WM_INIT_DIALOG:
        GUI_UC_SetEncodeUTF8();
        //初始化16字体大小的文字

//				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);  //体温
//        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
//        TEXT_SetTextColor(hItem, GUI_WHITE);
//        TEXT_SetText(hItem, "\xe5\xa9\xb4\xe5\x84\xbf\xe4\xbd\x93\xe6\xb8\xa9");
//        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_16);
//        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
//        TEXT_SetTextColor(hItem, GUI_WHITE);
//        TEXT_SetText(hItem, "\xe2\x84\x83");


        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe7\x8e\xaf\xe5\xa2\x83\xe6\xb8\xa9\xe5\xba\xa6");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe7\x8e\xaf\xe5\xa2\x83\xe6\xb9\xbf\xe5\xba\xa6");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "CO\xe6\xb5\x93\xe5\xba\xa6");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe5\x90\x90\xe5\xa5\xb6\xe6\xa3\x80\xe6\xb5\x8b");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe5\xb0\xbf\xe5\xba\x8a");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe6\x8d\x82\xe8\xa2\xab\xe5\xad\x90");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe2\x84\x83");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
        BUTTON_SetFont(hItem, &GUI_Fontsong16);//song16
        BUTTON_SetText(hItem, "\xe4\xb8\xbb\xe7\x95\x8c\xe9\x9d\xa2");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
        BUTTON_SetFont(hItem, &GUI_Fontsong16);//song16
        BUTTON_SetText(hItem, "\xe8\xae\xbe\xe5\xa4\x87\xe6\x8e\xa7\xe5\x88\xb6");
        //
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id)
        {
        case ID_BUTTON_3: // Notifications sent by 'Button'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        case ID_BUTTON_5: // Notifications sent by 'Button'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            case WM_NOTIFICATION_RELEASED:
                WM_HideWindow(g_environment_win); //隐藏Page0
                WM_HideWindow(g_equipment_win); //隐藏Page0
                WM_ShowWindow(g_main_win);//显示Page1
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_6: // Notifications sent by 'Button'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            case WM_NOTIFICATION_RELEASED:
                WM_HideWindow(g_environment_win); //隐藏Page0
                WM_HideWindow(g_main_win); //隐藏Page0
                WM_ShowWindow(g_equipment_win);//显示Page1
                // USER END
                break;
            }
            break;
        }
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}



/*********************************************************************
*
*      333333333333333333333333333333333333333333333333333333333
*/
/**/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate3[] =
{
    { WINDOW_CreateIndirect, "Window", ID_WINDOW_2, 1, 0, 240, 320, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "是否摇把", ID_BUTTON_7, 170, 225, 74, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "暖奶器", ID_BUTTON_8, 170, 115, 74, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "加湿器", ID_BUTTON_9, 170, 155, 74, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "负离子空气净化", ID_BUTTON_10, 170, 190, 74, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "下一页", ID_BUTTON_15, 90, 260, 74, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "主界面", ID_BUTTON_12, 20, 290, 74, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "环境参数", ID_BUTTON_13, 150, 290, 74, 30, 0, 0x0, 0 },
    { DROPDOWN_CreateIndirect, "Dropdown1", ID_DROPDOWN_0, 130, 80, 90, 30, 0, 0x0, 0 },

    { TEXT_CreateIndirect, "是否摇把", ID_TEXT_9, 60, 230, 100, 30, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "暖奶器", ID_TEXT_10, 60, 120, 100, 30, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "加湿器", ID_TEXT_11, 60, 160, 100, 30, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "净化器", ID_TEXT_12, 60, 195, 160, 30, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "音乐", ID_TEXT_14, 60, 80, 60, 30, 0, 0x0, 0 },

};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog3(WM_MESSAGE *pMsg)
{
    WM_HWIN      hItem;
    int NCode;
    int Id;
    int valu;
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        GUI_SetBkColor(GUI_DARKSLATEGRAY);//GUI_MYWIN1
        GUI_Clear();
        GUI_DrawBitmap(&bmtitle1, 0, 0);
        GUI_DrawBitmap(&bmmusic2, 10, 80);
        GUI_DrawBitmap(&bmmilkheater, 10, 120);
        GUI_DrawBitmap(&bmhumidifier, 10, 160);
        GUI_DrawBitmap(&bmcleanup, 10, 190);
        GUI_DrawBitmap(&bmswing, 10, 225);
        break;
    case WM_INIT_DIALOG:
        GUI_UC_SetEncodeUTF8();
        //初始化16字体大小的文字
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe6\x91\x87\xe6\x91\x86\xe5\x99\xa8");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe6\x9a\x96\xe5\xa5\xb6\xe5\x99\xa8");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe5\x8a\xa0\xe6\xb9\xbf\xe5\x99\xa8");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe5\x87\x80\xe5\x8c\x96\xe5\x99\xa8");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe5\xae\x89\xe5\x85\xa8\xe6\xa8\xa1\xe5\xbc\x8f");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe9\x9f\xb3\xe4\xb9\x90");
        // Initialization of 'Button'
        //
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
        BUTTON_SetBitmapEx(hItem, 0, &bmoff, 0, 0);
        BUTTON_SetText(hItem, "");  //在按钮上显示空
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
        BUTTON_SetBitmapEx(hItem, 0, &bmoff, 0, 0);
        BUTTON_SetText(hItem, "");  //在按钮上显示空
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
        BUTTON_SetBitmapEx(hItem, 0, &bmoff, 0, 0);
        BUTTON_SetText(hItem, "");  //在按钮上显示空
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
        BUTTON_SetBitmapEx(hItem, 0, &bmoff, 0, 0);
        BUTTON_SetText(hItem, "");  //在按钮上显示空
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
        BUTTON_SetBitmapEx(hItem, 0, &bmoff, 0, 0);
        BUTTON_SetText(hItem, "");  //在按钮上显示空
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
        BUTTON_SetFont(hItem, &GUI_Fontsong16);//song16
        BUTTON_SetText(hItem, "\xe4\xb8\xbb\xe7\x95\x8c\xe9\x9d\xa2");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
        BUTTON_SetFont(hItem, &GUI_Fontsong16);//song16
        BUTTON_SetText(hItem, "\xe7\x8e\xaf\xe5\xa2\x83\xe5\x8f\x82\xe6\x95\xb0");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_15);
        BUTTON_SetFont(hItem, &GUI_Fontsong16);//song16
        BUTTON_SetText(hItem, "\xe4\xb8\x8b\xe4\xb8\x80\xe9\xa1\xb5");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
        DROPDOWN_SetListHeight(hItem, 100);
        DROPDOWN_SetFont(hItem, &GUI_Fontsong16);
        DROPDOWN_AddString(hItem, "\xe5\x85\xb3");
        DROPDOWN_AddString(hItem, "\xe4\xb8\x96\xe4\xb8\x8a\xe5\x8f\xaa\xe6\x9c\x89\xe5\xa6\x88\xe5\xa6\x88\xe5\xa5\xbd");
        DROPDOWN_AddString(hItem, "\xe6\x95\xb0\xe9\xb8\xad\xe5\xad\x90");
        DROPDOWN_AddString(hItem, "\xe6\x8a\x93\xe6\xb3\xa5\xe9\xb3\x85");
        DROPDOWN_AddString(hItem, "\xe4\xb8\x8a\xe5\xad\xa6\xe6\xad\x8c");
        DROPDOWN_AddString(hItem, "\xe5\xb0\x8f\xe5\x85\x94\xe5\xad\x90\xe4\xb9\x96\xe4\xb9\x96");
        DROPDOWN_AddString(hItem, "\xe6\x91\x87\xe7\xaf\xae\xe6\x9b\xb2");
        DROPDOWN_SetAutoScroll(hItem, 1);
        DROPDOWN_SetScrollbarWidth(hItem, 20);
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id)
        {
        case ID_BUTTON_7: // Notifications sent by 'Button' 摇把器按键
            hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);  //获得按钮句柄!!!
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                /*更改皮肤*/
                BUTTON_SetBitmapEx(hItem, 0, app_control_mcu.valueswing_state ? &bmoff : &bmon, 0, 0);
                ///*标志位取反*/
                app_control_mcu.valueswing_state = !app_control_mcu.valueswing_state;
                ///*更改APP*/
                currentDataPoint.valueswing_state = app_control_mcu.valueswing_state;
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        case ID_BUTTON_8: // Notifications sent by 'Button'暖奶器按键
            hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);  //获得按钮句柄!!!
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                /*更改皮肤*/
                BUTTON_SetBitmapEx(hItem, 0, app_control_mcu.valueWarm_milk ? &bmoff : &bmon, 0, 0);
                ///*标志位取反*/
                app_control_mcu.valueWarm_milk = !app_control_mcu.valueWarm_milk;
                ///*更改APP*/
                currentDataPoint.valueWarm_milk = app_control_mcu.valueWarm_milk;
                break;
            }
            break;
        case ID_BUTTON_9: // Notifications sent by 'Button' 加湿器按键
            hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);  //获得按钮句柄!!!
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                /*更改皮肤*/
                BUTTON_SetBitmapEx(hItem, 0, app_control_mcu.valuehumidification ? &bmoff : &bmon, 0, 0);
                ///*标志位取反*/
                app_control_mcu.valuehumidification = !app_control_mcu.valuehumidification;
                ///*更改APP*/
                currentDataPoint.valuehumidification = app_control_mcu.valuehumidification;
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        case ID_BUTTON_10: // Notifications sent by 'Button' 净化器按键
            hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);  //获得按钮句柄!!!
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                /*更改皮肤*/
                BUTTON_SetBitmapEx(hItem, 0, app_control_mcu.valuepurifier ? &bmoff : &bmon, 0, 0);
                ///*标志位取反*/
                app_control_mcu.valuepurifier = !app_control_mcu.valuepurifier;
                ///*更改APP*/
                currentDataPoint.valuepurifier = app_control_mcu.valuepurifier;
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        case ID_BUTTON_11: // Notifications sent by 'Button'安全模式按键
            hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);  //获得按钮句柄!!!
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                /*更改皮肤*/
                BUTTON_SetBitmapEx(hItem, 0, app_control_mcu.valueweight_on_of ? &bmoff : &bmon, 0, 0);
                ///*标志位取反*/
                app_control_mcu.valueweight_on_of = !app_control_mcu.valueweight_on_of;
                ///*更改APP*/
                currentDataPoint.valueweight_on_of = app_control_mcu.valueweight_on_of;
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        case ID_BUTTON_12: // Notifications sent by 'Button' 主界面按键
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            case WM_NOTIFICATION_RELEASED:
                WM_HideWindow(g_environment_win); //隐藏Page0
                WM_HideWindow(g_equipment_win); //隐藏Page0
                WM_ShowWindow(g_main_win);//显示Page1
                // USER END
                break;
            }
            break;
        case ID_BUTTON_13: // Notifications sent by 'Button'环境参数按键
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                WM_HideWindow(g_equipment_win); //隐藏Page0
                WM_HideWindow(g_main_win); //隐藏Page0
                WM_ShowWindow(g_environment_win);//显示Page1
                // USER END
                break;
            }
            break;
        case ID_BUTTON_15: // Notifications sent by 'Button'下一页
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                WM_HideWindow(g_equipment_win); //隐藏Page0
                WM_HideWindow(g_main_win); //隐藏Page0
                WM_HideWindow(g_environment_win);
                WM_ShowWindow(g_baby_detection_win);//显示Page1
                // USER END
                break;
            }
            break;
        case ID_DROPDOWN_0: // Notifications sent by 'Dropdown1'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            case WM_NOTIFICATION_RELEASED:
                break;
            case WM_NOTIFICATION_SEL_CHANGED:
                hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
                valu = DROPDOWN_GetSel(hItem);
                currentDataPoint.valueplay_the_music = valu;
                app_control_mcu.valueplay_the_music = valu;
                break;
            }
            break;
        }
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}
/*********************************************************************
*
*      4444444444444444444444444444444444444444444444444444444
*/
/**/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate4[] =
{
    { WINDOW_CreateIndirect, "Window", ID_WINDOW_3, 1, 0, 240, 320, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "捂被子检测", ID_BUTTON_17, 170, 95, 74, 30, 0, 0x0, 0 },
    { EDIT_CreateIndirect, "捂被子", ID_EDIT_4, 180, 130, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "防偷模式", ID_BUTTON_19, 170, 20, 74, 30, 0, 0x0, 0 },
    { EDIT_CreateIndirect, "在车上", ID_EDIT_21, 180, 60, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "睡醒检测", ID_BUTTON_16, 170, 165, 74, 30, 0, 0x0, 0 },
    { EDIT_CreateIndirect, "睡醒", ID_EDIT_20, 180, 209, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "上一页", ID_BUTTON_15, 90, 260, 74, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "主界面", ID_BUTTON_12, 20, 290, 74, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "环境参数", ID_BUTTON_13, 150, 290, 74, 30, 0, 0x0, 0 },


    { TEXT_CreateIndirect, "捂被子检测", ID_TEXT_17, 60, 100, 100, 30, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "捂被子", ID_TEXT_18, 60, 135, 100, 30, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "防偷模式", ID_TEXT_19, 60, 20, 100, 30, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "在车上", ID_TEXT_20, 60, 63, 100, 30, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "睡醒检测", ID_TEXT_21, 60, 170, 160, 30, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "睡醒", ID_TEXT_22, 60, 208, 100, 30, 0, 0x0, 0 },

};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog4(WM_MESSAGE *pMsg)
{
    WM_HWIN      hItem;
    int NCode;
    int Id;
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        GUI_SetBkColor(GUI_DARKSLATEGRAY);//GUI_MYWIN1
        GUI_Clear();
        if (app_control_mcu.valueweight_on_of)
        {
            GUI_DrawBitmap(&bmLockon, 10, 20);
        }
        else
        {
            GUI_DrawBitmap(&bmLockoff, 10, 20);
        }
        GUI_DrawBitmap(&bmbabdsscd, 10, 100);
        GUI_DrawBitmap(&bmbabyssd, 10, 180);
        if (app_control_mcu.valuecover_the_quilt_switch)
        {
            if (app_control_mcu.valuecover_the_quilt == 2)                  //捂被子
            {
                hItem = pMsg->hWin;
                WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
                hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
                EDIT_SetBkColor(hItem, 1, GUI_YELLOW);
                EDIT_SetFont(hItem, &GUI_Fontsong22);//song16
                EDIT_SetTextColor(hItem, 1, GUI_RED);
                EDIT_SetText(hItem, " \xe6\x98\xaf");  //在按钮上显示空
            }
            else
            {
                hItem = pMsg->hWin;
                WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
                hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
                EDIT_SetBkColor(hItem, 1, GUI_WHITE);
                EDIT_SetFont(hItem, &GUI_Fontsong22);//song16
                EDIT_SetTextColor(hItem, 1, GUI_BLACK);
                EDIT_SetText(hItem, "\xe5\x90\xa6"); //在按钮上显示空
            }
        }
        else
        {
            hItem = pMsg->hWin;
            WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
            hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
            EDIT_SetBkColor(hItem, 1, GUI_WHITE);
            EDIT_SetFont(hItem, &GUI_Fontsong22);//song16
            EDIT_SetTextColor(hItem, 1, GUI_BLACK);
            EDIT_SetText(hItem, "---"); //在按钮上显示空
            app_control_mcu.valuecover_the_quilt = 0;
            currentDataPoint.valuecover_the_quilt = 0;
        }
        if (app_control_mcu.valueweight_on_of)
        {
            if (app_control_mcu.valueon_the_bed == 2)                  //在车上
            {
                hItem = pMsg->hWin;
                WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
                hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_21);
                EDIT_SetBkColor(hItem, 1, GUI_YELLOW);
                EDIT_SetFont(hItem, &GUI_Fontsong22);//song16
                EDIT_SetTextColor(hItem, 1, GUI_RED);
                EDIT_SetText(hItem, " \xe5\x90\xa6"); //在按钮上显示空
            }
            else
            {
                hItem = pMsg->hWin;
                WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
                hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_21);
                EDIT_SetBkColor(hItem, 1, GUI_WHITE);
                EDIT_SetFont(hItem, &GUI_Fontsong22);//song16
                EDIT_SetTextColor(hItem, 1, GUI_BLACK);
                EDIT_SetText(hItem, "\xe6\x98\xaf"); //在按钮上显示空
            }
        }
        else
        {
            hItem = pMsg->hWin;
            WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
            hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_21);
            EDIT_SetBkColor(hItem, 1, GUI_WHITE);
            EDIT_SetFont(hItem, &GUI_Fontsong22);//song16
            EDIT_SetTextColor(hItem, 1, GUI_BLACK);
            EDIT_SetText(hItem, "---"); //在按钮上显示空
            app_control_mcu.valueon_the_bed = 0;
            currentDataPoint.valueon_the_bed = 0;
        }
        if (app_control_mcu.valuewake_up_testing_switch)
        {
            if (app_control_mcu.valuewake_up_testing == 2)                  //睡醒
            {
                hItem = pMsg->hWin;
                WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
                hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_20);
                EDIT_SetBkColor(hItem, 1, GUI_YELLOW);
                EDIT_SetFont(hItem, &GUI_Fontsong22);//song16
                EDIT_SetTextColor(hItem, 1, GUI_RED);
                EDIT_SetText(hItem, "\xe6\x98\xaf");  //在按钮上显示空
            }
            else
            {
                hItem = pMsg->hWin;
                WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
                hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_20);
                EDIT_SetBkColor(hItem, 1, GUI_WHITE);
                EDIT_SetFont(hItem, &GUI_Fontsong22);//song16
                EDIT_SetTextColor(hItem, 1, GUI_BLACK);
                EDIT_SetText(hItem, "\xe5\x90\xa6");  //在按钮上显示空
            }
        }
        else
        {
            hItem = pMsg->hWin;
            WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
            hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_20);
            EDIT_SetBkColor(hItem, 1, GUI_WHITE);
            EDIT_SetFont(hItem, &GUI_Fontsong22);//song16
            EDIT_SetTextColor(hItem, 1, GUI_BLACK);
            EDIT_SetText(hItem, "---");  //在按钮上显示空
            app_control_mcu.valuewake_up_testing = 0;
            currentDataPoint.valuewake_up_testing = 0;
        }
        break;
    case WM_INIT_DIALOG:
        GUI_UC_SetEncodeUTF8();
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_17);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe6\x8d\x82\xe8\xa2\xab\xe6\xa3\x80\xe6\xb5\x8b");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_18);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe6\x8d\x82\xe8\xa2\xab\xe5\xad\x90");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_19);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe9\x98\xb2\xe5\x81\xb7\xe6\xa8\xa1\xe5\xbc\x8f");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_20);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe5\x9c\xa8\xe8\xbd\xa6\xe4\xb8\x8a");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_21);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe7\x9d\xa1\xe9\x86\x92\xe6\xa3\x80\xe6\xb5\x8b");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_22);
        TEXT_SetFont(hItem, &GUI_Fontsong22);//song16
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "\xe7\x9d\xa1\xe9\x86\x92");
        //
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_17);
        BUTTON_SetBitmapEx(hItem, 0, &bmoff, 0, 0);
        BUTTON_SetText(hItem, "");  //在按钮上显示空
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_19);
        BUTTON_SetBitmapEx(hItem, 0, &bmoff, 0, 0);
        BUTTON_SetText(hItem, "");  //在按钮上显示空
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_DARKSLATEGRAY);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_16);
        BUTTON_SetBitmapEx(hItem, 0, &bmoff, 0, 0);
        BUTTON_SetText(hItem, "");  //在按钮上显示空
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
        BUTTON_SetFont(hItem, &GUI_Fontsong16);//song16
        BUTTON_SetText(hItem, "\xe4\xb8\xbb\xe7\x95\x8c\xe9\x9d\xa2");
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
        BUTTON_SetFont(hItem, &GUI_Fontsong16);//song16
        BUTTON_SetText(hItem, "\xe7\x8e\xaf\xe5\xa2\x83\xe5\x8f\x82\xe6\x95\xb0");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_15);
        BUTTON_SetFont(hItem, &GUI_Fontsong16);//song16
        BUTTON_SetText(hItem, "\xe4\xb8\x8a\xe4\xb8\x80\xe9\xa1\xb5");
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id)
        {
        case ID_BUTTON_17: // Notifications sent by 'Button' 捂被子检测
            hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_17);  //获得按钮句柄!!!
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                /*更改皮肤*/
                BUTTON_SetBitmapEx(hItem, 0, app_control_mcu.valuecover_the_quilt_switch ? &bmoff : &bmon, 0, 0);
                ///*标志位取反*/
                app_control_mcu.valuecover_the_quilt_switch = !app_control_mcu.valuecover_the_quilt_switch;
                ///*更改APP*/
                currentDataPoint.valuecover_the_quilt_switch = app_control_mcu.valuecover_the_quilt_switch;
                currentDataPoint.valuecover_the_quilt = 1;
                app_control_mcu.valuecover_the_quilt = 1;
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        case ID_BUTTON_19: // Notifications sent by 'Button'防偷模式
            hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_19);  //获得按钮句柄!!!
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                /*更改皮肤*/
                BUTTON_SetBitmapEx(hItem, 0, app_control_mcu.valueweight_on_of ? &bmoff : &bmon, 0, 0);
                ///*标志位取反*/
                app_control_mcu.valueweight_on_of = !app_control_mcu.valueweight_on_of;
                ///*更改APP*/
                currentDataPoint.valueweight_on_of = app_control_mcu.valueweight_on_of;
                currentDataPoint.valueon_the_bed = 1;
                app_control_mcu.valueon_the_bed = 1;
                break;
            }
            break;
        case ID_BUTTON_16: // Notifications sent by 'Button' 睡醒检测
            hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_16);  //获得按钮句柄!!!
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                /*更改皮肤*/
                BUTTON_SetBitmapEx(hItem, 0, app_control_mcu.valuewake_up_testing_switch ? &bmoff : &bmon, 0, 0);
                ///*标志位取反*/
                app_control_mcu.valuewake_up_testing_switch = !app_control_mcu.valuewake_up_testing_switch;
                ///*更改APP*/
                currentDataPoint.valuewake_up_testing_switch = app_control_mcu.valuewake_up_testing_switch;
                currentDataPoint.valuewake_up_testing = 1;
                app_control_mcu.valuewake_up_testing = 1;
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                break;
            }
            break;
        case ID_BUTTON_12: // Notifications sent by 'Button' 主界面按键
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                WM_HideWindow(g_environment_win); //隐藏Page0
                WM_HideWindow(g_equipment_win); //隐藏Page0
                WM_ShowWindow(g_main_win);//显示Page1
                // USER END
                break;
            }
            break;
        case ID_BUTTON_13: // Notifications sent by 'Button'环境参数按键
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                WM_HideWindow(g_equipment_win); //隐藏Page0
                WM_HideWindow(g_main_win); //隐藏Page0
                WM_HideWindow(g_baby_detection_win); //隐藏Page0
                WM_ShowWindow(g_environment_win);//显示Page1
                // USER END
                break;
            }
            break;
        case ID_BUTTON_15: // Notifications sent by 'Button'下一页按键
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                WM_ShowWindow(g_equipment_win); //隐藏Page0
                WM_HideWindow(g_main_win); //隐藏Page0
                WM_HideWindow(g_baby_detection_win); //隐藏Page0
                WM_HideWindow(g_environment_win);//显示Page1
                // USER END
                break;
            }
            break;
        }
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}
/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

void CreateWindow(void)
{
    g_main_win = GUI_CreateDialogBox(_aDialogCreate1, GUI_COUNTOF(_aDialogCreate1), _cbDialog1, WM_HBKWIN, 0, 0);
    g_environment_win = GUI_CreateDialogBox(_aDialogCreate2, GUI_COUNTOF(_aDialogCreate2), _cbDialog2, WM_HBKWIN, 0, 0);
    g_equipment_win = GUI_CreateDialogBox(_aDialogCreate3, GUI_COUNTOF(_aDialogCreate3), _cbDialog3, WM_HBKWIN, 0, 0);
    g_baby_detection_win = GUI_CreateDialogBox(_aDialogCreate4, GUI_COUNTOF(_aDialogCreate4), _cbDialog4, WM_HBKWIN, 0, 0);
}

void MainTask1(void)
{
    CreateWindow();
    while (1)
    {
        GUI_Delay(100);
    }
}


/*************************** End of file ****************************/
